name: Build and Publish Packaged Release

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tag-with-incremented-patch-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Tag with Incremented Patch Version
        id: tag-with-incremented-patch-version
        run: |
          echo "Fetching git tags"
          git fetch --prune --unshallow --tags
          echo "Tagging with incremented patch number"
          bash ./scripts/tag_git_dev.sh

  create-release:
    needs: tag-with-incremented-patch-version
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          body: |
            Tagged release ${{ github.ref }}

  build-and-publish:
    needs: tag-with-incremented-patch-version
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://npm.pkg.github.com'
          scope: "@OWNER"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-java@v1
        with:
          java-version: '8'
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Install Jekyll
        run: |
          gem install bundler
          bundle install
      - name: Update Publisher executable
        run: bash _updatePublisher.sh --force --yes --skip-ping
      - name: Generate Implementation Guide (IG)
        run: bash _genonce.sh
      - name: Install NPM modules
        run: npm ci
      - name: Publish to Package Repository
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash _publishToRepo.sh --release-version ${{ github.ref }}
