name: Tag with New Patch Version

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Tag with Incremented Patch Version
        id: tag_with_incremented_patch_version
        run: |
          echo "Fetching git tags"
          git fetch --prune --unshallow --tags
          echo "Tagging with incremented patch number"
          bash ./scripts/tag_git_dev.sh